const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    //gender
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
    //role
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',
    //position
    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    //all users
    FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    //top doctor
    FETCH_TOP_DOCTOR_HOME_START: 'FETCH_TOP_DOCTOR_HOME_START',
    FETCH_TOP_DOCTOR_HOME_SUCCESS: 'FETCH_TOP_DOCTOR_HOME_SUCCESS',
    FETCH_TOP_DOCTOR_HOME_FAILED: 'FETCH_TOP_DOCTOR_HOME_FAILED',

    //all doctor
    FETCH_ALL_DOCTORS_START: 'FETCH_ALL_DOCTORS_START',
    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

    //save info doctor
    SAVE_INFO_DOCTOR_START: 'SAVE_INFO_DOCTOR_START',
    SAVE_INFO_DOCTOR_SUCCESS: 'SAVE_INFO_DOCTOR_SUCCESS',
    SAVE_INFO_DOCTOR_FAILED: 'SAVE_INFO_DOCTOR_FAILED',

    //get detail doctor
    GET_DETAIL_DOCTOR_START: 'GET_DETAIL_DOCTOR_START',
    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAILED: 'GET_DETAIL_DOCTOR_FAILED',

    //Get all code schedule
    FETCH_ALL_CODE_SCHEDULE_TIME_START: 'FETCH_ALL_CODE_SCHEDULE_TIME_START',
    FETCH_ALL_CODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALL_CODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALL_CODE_SCHEDULE_TIME_FAILED: 'FETCH_ALL_CODE_SCHEDULE_TIME_FAILED',

    //save bulk schedule
    SAVE_BULK_SCHEDULE_DOCTOR_START: 'SAVE_BULK_SCHEDULE_DOCTOR_START',
    SAVE_BULK_SCHEDULE_DOCTOR_SUCCESS: 'SAVE_BULK_SCHEDULE_DOCTOR_SUCCESS',
    SAVE_BULK_SCHEDULE_DOCTOR_FAILED: 'SAVE_BULK_SCHEDULE_DOCTOR_FAILED',

    //get doctor schedule
    FETCH_DOCTOR_SCHEDULE_START: 'FETCH_DOCTOR_SCHEDULE_START',
    FETCH_DOCTOR_SCHEDULE_SUCCESS: 'FETCH_DOCTOR_SCHEDULE_SUCCESS',
    FETCH_DOCTOR_SCHEDULE_FAILED: 'FETCH_DOCTOR_SCHEDULE_FAILED',

    //get required doctor info
    FETCH_REQUIRED_DOCTOR_INFO_START: 'FETCH_REQUIRED_DOCTOR_INFO_START',
    FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFO_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFO_FAILED: 'FETCH_REQUIRED_DOCTOR_INFO_FAILED',

    //get extra info doctor by id
    FETCH_EXTRA_DOCTOR_INFO_START: 'FETCH_EXTRA_DOCTOR_INFO_START',
    FETCH_EXTRA_DOCTOR_INFO_SUCCESS: 'FETCH_EXTRA_DOCTOR_INFO_SUCCESS',
    FETCH_EXTRA_DOCTOR_INFO_FAILED: 'FETCH_EXTRA_DOCTOR_INFO_FAILED',

    //SAVE PATIENTBOOKINGAPPOINTMENT
    SAVE_PATIENT_BOOKING_APPOINTMENT_START: 'SAVE_PATIENT_BOOKING_APPOINTMENT_START',
    SAVE_PATIENT_BOOKING_APPOINTMENT_SUCCESS: 'SAVE_PATIENT_BOOKING_APPOINTMENT_SUCCESS',
    SAVE_PATIENT_BOOKING_APPOINTMENT_FAILED: 'SAVE_PATIENT_BOOKING_APPOINTMENT_FAILED',

    //POST VERIFY BOOK APPOINTMENT
    POST_VERIFY_BOOK_APPOINTMENT_START: 'POST_VERIFY_BOOK_APPOINTMENT_START',
    POST_VERIFY_BOOK_APPOINTMENT_SUCCESS: 'POST_VERIFY_BOOK_APPOINTMENT_SUCCESS',
    POST_VERIFY_BOOK_APPOINTMENT_FAILED: 'POST_VERIFY_BOOK_APPOINTMENT_FAILED',
    
    //CREATE NEW SPECIALTY
    CREATE_NEW_SPECIALTY_START: 'CREATE_NEW_SPECIALTY_START',
    CREATE_NEW_SPECIALTY_SUCCESS: 'CREATE_NEW_SPECIALTY_SUCCESS',
    CREATE_NEW_SPECIALTY_FAILED: 'CREATE_NEW_SPECIALTY_FAILED',

    //FETCH ALL SPECIALTY
    FETCH_ALL_SPECIALTY_START: 'FETCH_ALL_SPECIALTY_START',
    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',
    FETCH_ALL_SPECIALTY_FAILED: 'FETCH_ALL_SPECIALTY_FAILED',

    //GET DETAILS SPECIALTY BY ID
    GET_DETAILS_SPECIALTY_BY_ID_START: 'GET_DETAILS_SPECIALTY_BY_ID_START',
    GET_DETAILS_SPECIALTY_BY_ID_SUCCESS: 'GET_DETAILS_SPECIALTY_BY_ID_SUCCESS',
    GET_DETAILS_SPECIALTY_BY_ID_FAILED: 'GET_DETAILS_SPECIALTY_BY_ID_FAILED',

    //CREATE NEW CLINIC
    CREATE_NEW_CLINIC_START: 'CREATE_NEW_CLINIC_START',
    CREATE_NEW_CLINIC_SUCCESS: 'CREATE_NEW_CLINIC_SUCCESS',
    CREATE_NEW_CLINIC_FAILED: 'CREATE_NEW_CLINIC_FAILED',

    //FETCH ALL CLINIC
    FETCH_ALL_CLINIC_START: 'FETCH_ALL_CLINIC_START',
    FETCH_ALL_CLINIC_SUCCESS: 'FETCH_ALL_CLINIC_SUCCESS',
    FETCH_ALL_CLINIC_FAILED: 'FETCH_ALL_CLINIC_FAILED',

    //GET DETAILS CLINIC BY ID
    GET_DETAILS_CLINIC_BY_ID_START: 'GET_DETAILS_CLINIC_BY_ID_START',
    GET_DETAILS_CLINIC_BY_ID_SUCCESS: 'GET_DETAILS_CLINIC_BY_ID_SUCCESS',
    GET_DETAILS_CLINIC_BY_ID_FAILED: 'GET_DETAILS_CLINIC_BY_ID_FAILED',

    //FETCH ALL CLINIC REDUX
    FETCH_ALL_CLINIC_REDUX_START: 'FETCH_ALL_CLINIC_REDUX_START',
    FETCH_ALL_CLINIC_REDUX_SUCCESS: 'FETCH_ALL_CLINIC_REDUX_SUCCESS',
    FETCH_ALL_CLINIC_REDUX_FAILED: 'FETCH_ALL_CLINIC_REDUX_FAILED',

    //DELETE CLINIC REDUX
    DELETE_CLINIC_REDUX_START: 'DELETE_CLINIC_REDUX_START',
    DELETE_CLINIC_REDUX_SUCCESS: 'DELETE_CLINIC_REDUX_SUCCESS',
    DELETE_CLINIC_REDUX_FAILED: 'DELETE_CLINIC_REDUX_FAILED',  

    //EDIT CLINIC REDUX
    EDIT_CLINIC_REDUX_START: 'EDIT_CLINIC_REDUX_START',
    EDIT_CLINIC_REDUX_SUCCESS: 'EDIT_CLINIC_REDUX_SUCCESS',
    EDIT_CLINIC_REDUX_FAILED: 'EDIT_CLINIC_REDUX_FAILED',

    //DELETE SPECIALTY REDUX
    DELETE_SPECIALTY_REDUX_START: 'DELETE_SPECIALTY_REDUX_START',
    DELETE_SPECIALTY_REDUX_SUCCESS: 'DELETE_SPECIALTY_REDUX_SUCCESS',
    DELETE_SPECIALTY_REDUX_FAILED: 'DELETE_SPECIALTY_REDUX_FAILED',

    //EDIT SPECIALTY REDUX
    EDIT_SPECIALTY_REDUX_START: 'EDIT_SPECIALTY_REDUX_START',   
    EDIT_SPECIALTY_REDUX_SUCCESS: 'EDIT_SPECIALTY_REDUX_SUCCESS',
    EDIT_SPECIALTY_REDUX_FAILED: 'EDIT_SPECIALTY_REDUX_FAILED',

    //GET LIST PATIENT FOR DOCTOR
    GET_LIST_PATIENT_FOR_DOCTOR_START:'GET_LIST_PATIENT_FOR_DOCTOR_START',
    GET_LIST_PATIENT_FOR_DOCTOR_SUCCESS:'GET_LIST_PATIENT_FOR_DOCTOR_SUCCESS',
    GET_LIST_PATIENT_FOR_DOCTOR_FAILED:'GET_LIST_PATIENT_FOR_DOCTOR_FAILED',
    
})

export default actionTypes;